version: '3.8'

services:
  web:
    build: .
    ports:
      - "27755:27755"
    volumes:
      - ./:/app:delegated
    environment:
      - DATABASE_TYPE=postgresql
      - POSTGRESQL_DATABASE_NAME=${DB_NAME}
      - POSTGRESQL_USER=${DB_USERNAME}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_HOST=db
      - POSTGRESQL_PORT=5432
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    container_name: postgresql
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    restart: always

  meilisearch:
    image: getmeili/meilisearch:v1.15
    container_name: meili
    ports: 
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
volumes:
  postgres_data: 