version: '3.8'

services:
  web:
    build: .
    ports:
      - "27755:27755"
    volumes:
      - ./:/app:delegated
    environment:
      - DATABASE_TYPE=postgresql
      - POSTGRESQL_DATABASE_NAME=storagebucket
      - POSTGRESQL_USER=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_HOST=db
      - POSTGRESQL_PORT=5432
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    container_name: postgresql
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=storagebucket
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    restart: always

  meilisearch:
    image: getmeili/meilisearch:v1.15
    container_name: meili
    ports: 
      - "7700:7700"


volumes:
  postgres_data: 