services:

  db:
    image: postgres:15
    volumes:
      - /mnt/myssd/storagebucket/postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    restart: always
  web:
    build: .
    ports:
      - "${WEB_PORT}:8000"
    volumes:
      - ./:/app:delegated
    environment:
      - DATABASE_TYPE=sqlite
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    depends_on:
      - db

  meilisearch:
    image: getmeili/meilisearch:v1.15
    container_name: meili
    ports: 
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
volumes:
  postgres_data: 